theme: jekyll-theme-slate
site_favicon: favicon.ico
title: Bempp
description: Boundary element method Python package
bemppversion: Bempp-cl 0.2.3

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

include: ["handbook","_images","_sources","_static"]
